version: '3'

services:
  app:
    build: .
    container_name: app
    image: wtf-app
    env_file: .env
    environment:
      - NODE_ENV=$NODE_ENV
      - MONGODB_URI=$MONGODB_URI
      - JWT_SECRET=$JWT_SECRET
    restart: always
    ports:
      - '80:3000'
