version: '3'

services:
  app:
    build: .
    container_name: app
    environment:
      - NODE_ENV=${NODE_ENV}
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
    restart: always
    ports:
      - '3000:3000'
