// AUTH
export const SET_AUTH_LOADING = 'SET_AUTH_LOADING'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT = 'LOGOUT'
export const USER_LOADED = 'USER_LOADED'
export const USERS_LOADED = 'USERS_LOADED'
export const AUTH_ERROR = 'AUTH_ERROR'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'

// CHALLENGES
export const SET_CHALLENGES_LOADING = 'SET_CHALLENGES_LOADING'
export const CHALLENGE_LOADED = 'CHALLENGE_LOADED'
export const CHALLENGES_LOADED = 'CHALLENGES_LOADED'
export const CHALLENGE_OF_THE_WEEK_LOADED = 'CHALLENGE_OF_THE_WEEK_LOADED'
export const CLEAR_CHALLENGE = 'CLEAR_CHALLENGE'
export const RESULT_SUBMITTED = 'RESULT_SUBMITTED'
